on: push

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   ref: master
      - name: Package
        run: |
          npm install
          npm ci
          npm run package
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "chore: Update dist (${{ github.event.pull_request.title }})" || echo "No changes to commit"
          git push origin
